### ISSUE TITLE
Bug, Dependencies messed up during edit

### ISSUE THREAD

**Issue by crynobone** [UserScape/Laravel-Bundles#52]
Refer http://d.pr/i/odyB

It works fine during adding a bundle, but once you want to edit it, the app assume 'Laravel Hybrid Bundle' as 3 different bundle instead of just a single bundle.

**Comment by ericlbarnes** [comment]
Thanks for the report.  I can't get to this until next week but will get the fix up then.

**Comment by ericlbarnes** [comment]
crynobone> adding is fine, just during update
crynobone> it separate the title by space
crynobone> 1 single dependencies become 3
crynobone> I think it better to just use name rather than title

daylerees> ericbarnes: not sure if not saving dependencies, or using the wrong field when serving them from the api
daylerees> maybe its sending title rather than install stub

crynobone> it's only happen if you have bundle title with space
crynobone> so using name (I assume it's unique) solve everything
